# Generated by Django 5.0 on 2025-03-11 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('serie_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de Série')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de Custo')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de Venda')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacionalidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brands.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
